name: Clang Tidy Code Review

on: [pull_request]

jobs:
  review:
    name: Code review by Clang Tidy
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: "Install dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-9 clang-tidy-9 libboost-all-dev python3-setuptools

      - name: "Perform code review"
        run: |
          pip3 install unidiff
          pip3 install PyGithub
          pip3 install requests
          python3 .ci/clang-tidy-review.py --repo ${{ github.repository }} --pr ${{ github.event.pull_request.number }} --clang_tidy_binary clang-tidy-9 --token ${{ github.token }} --include "include/boost/numeric/ublas/tensor/*.hpp,include/boost/numeric/ublas/tensor/*/*.hpp,example/tensor/*.cpp"
      #- name: "Run clang-tidy check"
      #  run: |
      #    clang-tidy-9 examples/tensor/*.cpp -- -Iinclude -std=c++17
