name: Clang tidy checks

on: [push]

jobs:
  check:
    name: Clang tidy Check 
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        
      - name: "Install dependencies"
        run: |
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo apt-get update
          sudo apt-add-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main"
          sudo apt-get install -y clang-10 clang-tidy-10 libboost-all-dev

      - name: "Run clang-tidy check"
        run: |
          clang-tidy-10 examples/tensor/*.cpp -- -Iinclude -std=c++17 > reports.txt

      - name: "Show clang tidy report"
        if: always()  
        run: |
          cat reports.txt

