name: Linux Clang
# Trigger on Push to the repository, regardless of the branch.
# For fine tune, You can add specific branches or tags.
on: [pull_request]
  
jobs:
  build:
    name: "${{matrix.config.cxx}} -std=c++${{matrix.config.cxxstd}}"
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      # If any compiler fails to compile, continue CI for next compiler in matrix instead of failing early
      matrix:
        config: 
          - { cc: clang-6.0, cxx: clang++-6.0, cxxstd: 11}
          - { cc: clang-8, cxx: clang++-8, cxxstd: 11}
          - { cc: clang-9, cxx: clang++-9, cxxstd: 11}
          - { cc: clang-10, cxx: clang++-10, cxxstd: 11}
          - { cc: clang-6.0, cxx: clang++-6.0, cxxstd: 17}
          - { cc: clang-8, cxx: clang++-8, cxxstd: 17}
          - { cc: clang-9, cxx: clang++-9, cxxstd: 17}
          - { cc: clang-10, cxx: clang++-10, cxxstd: 17}
          - { cc: clang-10, cxx: clang++-10, cxxstd: 2a}
         
    steps:
    - uses: actions/checkout@v2
      # Checks out the source code, if not done, runner will not clone the repository
    
    - name: Install Clang 10
      if: matrix.config.cxx == 'clang++-10'
      run: |
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo apt-get update
        sudo apt-add-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main"
        sudo apt-get install -y clang-10
      
    - name: Set Environment Variables
      run: |
         echo ::set-env name=CC::${{matrix.config.cc}}
         echo ::set-env name=CXX::${{matrix.config.cxx}}
        
    - name: Prepare BOOST_ROOT
      run: |
        cd ${GITHUB_WORKSPACE}
        cd ..
        
        git clone -b master --depth 1 https://github.com/boostorg/boost.git boost-root
        cd boost-root
        
        git submodule update --init --jobs 8 tools/build
        git submodule update --init --jobs 8 libs/config
        git submodule update --init --jobs 8 tools/boostdep
        
        mkdir -p libs/numeric/
        cp -rp ${GITHUB_WORKSPACE}/. libs/numeric/ublas
        python tools/boostdep/depinst/depinst.py -I benchmarks numeric/ublas
        
        ./bootstrap.sh
        ./b2 -j 8 headers
        
        echo ::set-env name=BOOST_ROOT::${PWD}
        
    - name: Prepare Build
      run: |
        echo $BOOST_ROOT
        cd $BOOST_ROOT
        
        echo "using clang : : ${{ matrix.config.cxx }} ;" >> ~/user-config.jam;
        echo "using clblas : : <include>${CLBLAS_PREFIX}/include <search>${CLBLAS_PREFIX}/lib ;" >> ~/user-config.jam;
        
        cat ~/user-config.jam
        
        cp ${GITHUB_WORKSPACE}/opencl.jam ~/
        cp ${GITHUB_WORKSPACE}/clblas.jam ~/
        
    - name: Test Benchmarks
      run: |
        cd $BOOST_ROOT
        cd libs/numeric/ublas
        $BOOST_ROOT/b2 -j 4 benchmarks toolset=clang cxxstd=${{matrix.config.cxxstd}}
        
    - name: Test Tensor Examples
      if: matrix.config.cxxstd == '17' || matrix.config.cxxstd == '2a'
      run: |
        cd $BOOST_ROOT
        cd libs/numeric/ublas
        $BOOST_ROOT/b2 -j 4 examples/tensor toolset=clang cxxstd=${{matrix.config.cxxstd}}
        
    - name: Test Tensor
      if: matrix.config.cxxstd == '17' || matrix.config.cxxstd == '2a'
      run: |
        cd $BOOST_ROOT
        cd libs/numeric/ublas
        $BOOST_ROOT/b2 -j 4 test/tensor toolset=clang cxxstd=${{matrix.config.cxxstd}}
        
    - name: Test uBLAS
      run: |
        cd $BOOST_ROOT
        cd libs/numeric/ublas
        $BOOST_ROOT/b2 -j 4 test toolset=clang cxxstd=${{matrix.config.cxxstd}}
