name: Linux C++20
# Trigger on Push to the repository, regardless of the branch.
# For fine tune, You can add specific branches or tags.
on: [push, pull_request]
  
jobs:
  build:
    name: "${{matrix.config.cxx}} -std=c++${{matrix.cxxstd}}"
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      # If any compiler fails to compile, continue CI for next compiler in matrix instead of failing early
      matrix:
        cxxstd: [11, 17, 2a]
        config: 
          - { cc: gcc-10, cxx: g++-10, toolset: gcc }
          - { cc: clang-10, cxx: clang++-10, toolset: clang }
            
    steps:
    - uses: actions/checkout@v2
      # Checks out the source code, if not done, runner will not clone the repository
        
    - name: Set Environment Variables
      run: |
         echo ::set-env name=CLBLAS_PREFIX::${GITHUB_WORKSPACE}/CLBLAS
         echo ::set-env name=PATH::${GITHUB_WORKSPACE}/CLBLAS/bin:${PATH}
         echo ::set-env name=LD_LIBRARY_PATH::${GITHUB_WORKSPACE}/CLBLAS/lib:${LD_LIBRARY_PATH}
         
         echo ::set-env name=CC::${{matrix.config.cc}}
         echo ::set-env name=CXX::${{matrix.config.cxx}}
        
    - name: Install GCC-10
      if: matrix.config.cxx == 'g++-10'
      # Only run this step if g++-10 is found from matrix strategy
      run: |
         sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
         sudo apt update
         sudo apt-get install -y g++-10
         
    - name: Install Clang-10
      if: matrix.config.cxx == 'clang++-10' 
      # Only run this step if clang++-10 is found from matrix strategy
      run: |
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo apt-get update
        sudo apt-add-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main"
        sudo apt-get install -y clang-10
        
    - name: Prepare BOOST_ROOT
      run: |
        cd ${GITHUB_WORKSPACE}
        cd ..
        
        git clone -b master --depth 1 https://github.com/boostorg/boost.git boost-root
        cd boost-root
        
        git submodule update --init --jobs 8 tools/build
        git submodule update --init --jobs 8 libs/config
        git submodule update --init --jobs 8 tools/boostdep
        
        mkdir -p libs/numeric/
        cp -rp ${GITHUB_WORKSPACE}/. libs/numeric/ublas
        python tools/boostdep/depinst/depinst.py -I benchmarks numeric/ublas
        
        ./bootstrap.sh
        ./b2 -j 8 headers
        
        echo ::set-env name=BOOST_ROOT::${PWD}
        
    - name: Prepare Build
      run: |
        echo $BOOST_ROOT
        cd $BOOST_ROOT
        
        echo "using ${{ matrix.config.toolset }} : : ${{ matrix.config.cxx }} ;" >> ~/user-config.jam;
        echo "using clblas : : <include>${CLBLAS_PREFIX}/include <search>${CLBLAS_PREFIX}/lib ;" >> ~/user-config.jam;
        
        cat ~/user-config.jam
        
        cp ${GITHUB_WORKSPACE}/opencl.jam ~/
        cp ${GITHUB_WORKSPACE}/clblas.jam ~/
        
    - name: Test Benchmarks
      run: |
        cd $BOOST_ROOT
        cd libs/numeric/ublas
        $BOOST_ROOT/b2 -j 4 benchmarks toolset=${{matrix.config.toolset}} cxxstd=${{matrix.cxxstd}}
        
    - name: Test Tensor Examples
      run: |
        cd $BOOST_ROOT
        cd libs/numeric/ublas
        $BOOST_ROOT/b2 -j 4 examples/tensor toolset=${{matrix.config.toolset}} cxxstd=${{matrix.cxxstd}}
        
    - name: Test Tensor
      run: |
        cd $BOOST_ROOT
        cd libs/numeric/ublas
        $BOOST_ROOT/b2 -j 4 test/tensor toolset=${{matrix.config.toolset}} cxxstd=${{matrix.cxxstd}}

    - name: Test uBLAS
      run: |
        cd $BOOST_ROOT
        cd libs/numeric/ublas
        $BOOST_ROOT/b2 -j 4 test toolset=${{matrix.config.toolset}} cxxstd=${{matrix.cxxstd}}
        
